### ISSUE TITLE
IMPORTANT: Game does not run outside of BlueJ and VScode

### ISSUE THREAD

**Issue by rhmhendriks** [rhmhendriks/ZUUL#34]
The game does not run outside of BlueJ and VScode anymore!

![image](https://user-images.githubusercontent.com/58547191/72840923-9670f400-3c95-11ea-8bae-5bc2bb571aca.png)

**This issue is of the highest priority**

@Bob3421 @luc9willemse  Please confirm my findings: open the project folder in a CMD/terminal window and use "java Game.java".

**Comment by nnaypey** [comment]
Solved multiple bugs to solve issue, see commit in testing
